// "use server"
import nodeMailer from "nodemailer";

export const sendEmail = async ({ email, subject, message }) => {
  const transporter = nodeMailer.createTransport({
    host: process.env.SMTP_HOST, // smtp.hostinger.com
    port: Number(process.env.SMTP_PORT), // must be a number like 465
    secure: true, // true for port 465 (SSL)
    auth: {
      user: process.env.SMTP_MAIL, // info@evolkun.com
      pass: process.env.SMTP_PASSWORD, // correct password (not your Hostinger login, but email-specific password)
    },
    // logger: true, 
    // debug: true, 
  });

  const options = {
    from: `"Evolkun" <${process.env.SMTP_MAIL}>`, // Optional display name
    to: email,
    subject,
    html: message,
  };

  await transporter.sendMail(options);
};

export const sendPlanToOwnerEmail = async ({
  userEmail,
  businessName,
  plans,
  voiceTranscript,
  userInput, // 🟢 added
}) => {
  const transporter = nodeMailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT),
    secure: true,
    auth: {
      user: process.env.SMTP_MAIL,
      pass: process.env.SMTP_PASSWORD,
    },
    // logger: true,
    // debug: true,
  });

  const planDetailsHtml = plans
    .map(
      (plan) => `
        <h3>${plan.name} — ${plan.price}</h3>
        <p><strong>Description:</strong> ${plan.description}</p>
        <ul>${plan.features.map((f) => `<li>${f}</li>`).join("")}</ul>
      `
    )
    .join("<hr/>");

  const message = `
    <p><strong>User Email:</strong> ${userEmail}</p>
    <p><strong>Business Name:</strong> ${businessName}</p>
    <p><strong>Voice Transcript:</strong><br/>"${voiceTranscript || "N/A"}"</p>
    <br/>
    <h2>Generated Plans</h2>
    ${planDetailsHtml}
    ${
      userInput
        ? `<p><strong>User Input:</strong> ${JSON.stringify(userInput)}</p>`
        : ""
    }
  `;

  const options = {
    from: `"Evolkun Notification" <${process.env.SMTP_MAIL}>`,
    to: process.env.SMTP_MAIL,
    subject: `🚀 New Plan Generated by ${userEmail}`,
    html: message,
  };

  await transporter.sendMail(options);
};